### ISSUE TITLE
Do you.. need hosting?

### ISSUE THREAD

**Issue by snaildos** [electron-userland/electron-build-service#13]
Good afternoon too the community, whoever runs this website and manages the DNS, can you please reply?
I'm offering too host the service (since it's not getting hosted).
So? Do you guys need help with hosting? Because, as of currently the service is down and it's fairly annoying.

**Comment by mmaietta** [comment]
@snaildos, I'm guessing it was intentionally dropped due to maintenance capacity, but it'd be nice to have an additional maintainer for the project.

@develar this one is in your court? 🙂

**Comment by snaildos** [comment]
I'm not a experienced programmer or anything, I'm a sysadmin myself. I'm happy to run electron-userland on my servers. I'm going to run this on my servers anyway, I was just wondering who actually owns the domain, maybe they could reroute if they want.

**Comment by snaildos** [comment]
Bad idea.
Many security flaws.
Expensive setup.
CI exists.
