### ISSUE TITLE
Add selfhosting documentation

### ISSUE THREAD

**Issue by ohlookitsderpy** [electron-userland/electron-build-service#6]
Hello!

It's mentioned in the ``README.md`` of ``electron-build-service`` that: 
> Self-hosted usage documentation can be added by request.

I would like to self-host an instance of the service, could you add documentation for how please?

Thanks!

**Comment by develar** [comment]
Could you please explain for what and why? It will help me to write more targeted docs.

Low-level step-by-step guide is already available in k8s dir: https://github.com/electron-userland/electron-build-service/tree/master/k8s

**Comment by ohlookitsderpy** [comment]
I'd like to host it on a server I use as it's faster for me and if the main electron.build instance goes down again then my building won't be interrupted. 

I didn't know there was a Kubernetes guide, but sadly I have no experience with it and it's a bit too low level for me. I would prefer a guide that allows me to just run command after command and (hopefully) get an instance up and running without putting too much load on the system.

**Comment by develar** [comment]
So, you work on a Windows machine and have a spare Linux machine, that can be used as a build server. Reasonable. Have your considered using [Docker](https://www.electron.build/multi-platform-build#build-electron-app-using-docker-on-a-local-machine)? Or, again, it is too complicated and error prone (env mapping, directory mapping and so on).

Ok. I will add docs how to run own instance (service will be packed as snap, to ensure that you are not required to install Docker in addition).

If you are in rush and want to deploy now, you can clone this repo and run (repo as working dir, docker and docker-compose are required to be installed)

```
SNAP_DESTRUCTIVE_MODE=true USE_EMBEDDED_ETCD=true BUILDER_HOST=0.0.0.0 docker-compose up --abort-on-container-exit --remove-orphans --renew-anon-volumes
``` 

and then set for electron-builder (envs on your Windows machine)

```
BUILD_AGENT_HOST=192.168.64.3
USE_BUILD_SERVICE_LOCAL_CA=true
```
replace `192.168.64.3` to IP of your server.

You can use `_REMOTE_BUILD=true` to force using of remote build service on macOS/Linux.

**Comment by ohlookitsderpy** [comment]
Thank you for the instructions! <3

I haven't used Docker before, but it's something I have wanted to learn for a while. I will test the Docker instructions this evening and give you the results.

**Comment by develar** [comment]
To be honest, `docker-compose` is not right way to run (it is more for dev), but as quick solution, it is ok. Because docker image `electronuserland/build-service-builder` requires TLS files (cert and key).

**Comment by ohlookitsderpy** [comment]
Ran the command, got this <img src='https://u.derpyenterprises.org/8f1c8a.png'>

(all deps are installed i think)

**Comment by develar** [comment]
`docker-compose --version`?

**Comment by ohlookitsderpy** [comment]
docker-compose version 1.8.0, build unknown (installed from Debian APT)

**Comment by develar** [comment]
It is old version. You can our try to update it, or wait several hours (maybe only tomorrow morning) and I will provide simple instructions.

**Comment by ohlookitsderpy** [comment]
Alright, thanks!

**Comment by develar** [comment]
Done — https://github.com/electron-userland/electron-build-service/blob/master/self-hosted.md

Please review, I think it is clear and easy ;)

**Comment by ohlookitsderpy** [comment]
Thank you!
